install.packages("stringr")
install.packages("useful")
install.packages("pROC")
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
drat:::addRepo("dmlc")
# install.packages("mxnet")
install.packages("magrittr")
install.packages("caret")
install.packages("doMC")
install.packages("dplyr")
